### ISSUE TITLE
Version 2.2.4 raises LoadError due to `index` missing.

### ISSUE THREAD

**Issue by chrisjohnson** [bkuhlmann/xdg#1]
## Overview
I tried to install tmuxinator, which depends on xdg (but doesn't specify that it should be <=2.2.3). `gem install tmuxinator` saw that xdg 2.2.4 was available and used that.

When I ran tmuxinator, I got the following error:

```
/Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `require_relative': cannot load such file -- /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg/index (LoadError)
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `<module:XDG>'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg.rb:26:in `<top (required)>'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/tmuxinator-1.1.0/lib/tmuxinator.rb:6:in `<top (required)>'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cjohnson/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/tmuxinator-1.1.0/bin/tmuxinator:5:in `<top (required)>'
        from /Users/cjohnson/.rbenv/versions/2.4.6/bin/tmuxinator:23:in `load'
        from /Users/cjohnson/.rbenv/versions/2.4.6/bin/tmuxinator:23:in `<main>'
```

I tried various ruby versions to be sure. I checked in `~/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/xdg-2.2.4/lib/xdg/` and saw that there was no index.rb

My hunch is the 2.2.4 version should just be pulled down. It doesn't seem to match the latest master from the original rubyworks repository which does include an index.rb so I'm not sure where it came from.

## Environment
macOS Mojave

**Comment by chrisjohnson** [comment]
I put this here because it seems like you're actively working on things, and so I assume you were the one who pushed that 2.2.4 version up (it says that May 21 2019 is the date it was pushed). If that wasn't you feel free to direct me elsewhere

**Comment by bkuhlmann** [comment]
:bow: @chrisjohnson. Digging into this now. This release was only meant to add a post install message but how the original gem packaged itself is not straightforward. I'll get out another patch tonight, though.

**Comment by bkuhlmann** [comment]
@chrisjohnson, @ryanmt, @g-arjones I've released 2.2.5 with the necessary patch. When you get a chance could you confirm all is well. It's important to note that I've *not* changed the implementation details. I've only added a post install message you'll see when installing the gem. It'll look like this:

> Development of this project has been transfered here: https://github.com/bkuhlmann/xdg. This will be the last version supported within the 2.2.x series. Be aware major breaking changes will be introduced in the upcoming 3.0.0 release (2019-06-01).

Otherwise, functionality should be identical even though I packaged both the 2.2.4 and 2.2.5 release with a new version of Bundler.

**Comment by g-arjones** [comment]
All great, thank you for taking the time.. 👍

**Comment by chrisjohnson** [comment]
Works well here! Thanks :)

**Comment by bkuhlmann** [comment]
Awesome, good to hear! I'm going to close this issue as resolved. Keep in mind the `3.0.0` release will introduce breaking changes (in a good way :wink:). You can always lock XDG at the 2.2.x level until you are ready to upgrade, though. Anyway, FYI.

**Comment by ryanmt** [comment]
:+1: here as well. Thanks for quickly resolving!
