### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by OSXLich-Doug** [bkuhlmann/xdg#3]
## Overview
Pessimistic gemspec ruby requirement ~> 2.7 prevents building 4.5.0 on released ruby 3.0

## Screenshots/Screencasts
None - CLI

## Steps to Recreate
rbenv install 3.0.0
rbenv global 3.0.0
gem install xdg -v 4.5.0

## Desired Behavior
Ability to install current rev of xdg gem on 3.0 rubies

## Environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.3
  - RUBY VERSION: 3.0.0 (2020-12-25 patchlevel 0)

All OS (Win, macOS, linux variants)

**Comment by bkuhlmann** [comment]
Hey @OSXLich-Doug. :wave: Yep, [XDG 5.0.0](https://github.com/bkuhlmann/xdg/releases/tag/5.0.0) has just been released and supports Ruby 3.0.0. :wink:
