### ISSUE TITLE
How can I check loaded version of XDG module?

### ISSUE THREAD

**Issue by depesz** [bkuhlmann/xdg#4]
## Overview

I have varying version of xdg loaded in many places - in one it's 2.2.5, in another it's 4.5.0. All depending on ruby version, I guess.

The problem is that they have very different APIs.

I can work around it, by adding version check, but I'd need to know how to find version of used XDG library.

Or, perhaps, how else should I know whether I can use, very convenient XDG['CONFIG'].find(), and where I have to iterate over XDG::Config.new.directories and check for file existence...

**Comment by bkuhlmann** [comment]
Hey, Hubert, nice to meet you. :wave: I've been subscribed to your PostgreSQL articles for some time.

If you are asking how to quickly determine which version of XDG supports which version of Ruby, that can be done several ways:

- [Versions](https://www.alchemists.io/projects/xdg/versions) - All version details are listed here. To match up which Ruby version XDG was upgraded to, you'd only need to search for the `Updated to Ruby` string to find what you need.
- [RubyGems](https://rubygems.org/gems/xdg/versions) - Same as above but you can click on each version to immediately see which version of Ruby is required.
- `XDG::Identity` - With XDG 2.2.4, the Identity module was introduced which had a constant that you could query for version information. Example: `XDG::Identity::VERSION`. As of XDG 6.1.0, though, that module has been removed in favor of using the `xdg.gemspec` only. Regardless, all versions from 2.2.4 to 6.1.0 use `XDG::Config.new`. Those prior to 2.2.4 use `XDG["CONFIG"]`.

Does that help?

**Comment by depesz** [comment]
Hmnmm .. I have 2.2.5, and when I tried XDG::Config.new:

```
[1] pry(main)> require 'xdg'
=> true

[2] pry(main)> XDG::Identity::VERSION
NameError: uninitialized constant XDG::Identity
from (pry):2:in `__pry__'

[3] pry(main)> XDG::Config.new
NameError: uninitialized constant XDG::Config
Did you mean?  RbConfig
from (pry):3:in `__pry__'

[4] pry(main)> XDG["CONFIG"]
=> #<XDG::BaseDir:0x00005610baaae0d0 @environment_variables=["XDG_CONFIG_HOME", "XDG_CONFIG_DIRS"]>

[5] pry(main)> Gem.loaded_specs["xdg"].version
=> Gem::Version.new("2.2.5")

```

So it looks that with 2.2.5 I don't have XDG::Config, and I don't have XDG::Identity :(

**Comment by depesz** [comment]
As a side note:

```
[10] pry(main)> XDG::VERSION
=> "2.2.3"
```

No idea what that means.

**Comment by bkuhlmann** [comment]
Ah, apologies. I see the problem now. I miss quoted you earlier. You must be on 3.0.0 or higher to leverage `XDG::Identity::VERSION`. I've updated my notes above so they make more sense. Anything prior to 3.0.0 is before my time of taking ownership of this gem and that code base was difficult to deal with which is why the Object API changed to be more manageable but also more testable.

In your case, I think you'd have everything you need by doing something close to the following. That should allow you to feature toggle your code as desired:

``` ruby
defined?(XDG::Config) ? "Using 3.0.0 or higher" : "Using 2.2.5 or lower"
```

**Comment by depesz** [comment]
That works. Thanks a lot.
