### ISSUE TITLE
Switch to SPDX approved license?

### ISSUE THREAD

**Issue by dcermak** [bkuhlmann/xdg#5]
## Overview

xdg uses the Hippocratic license at version 3.0, which currently prevents us from updating this gem in openSUSE, as we require all packages to be licensed under a license on the SPDX list. Would it be possible to go back to version 2.1? Otherwise we will most likely have to drop this gem.

Note, that I have also found https://github.com/spdx/license-list-XML/issues/1393, but it looks like version 3 is unlikely to get accepted.

**Comment by bkuhlmann** [comment]
OK, I've released [6.3.1](https://www.alchemists.io/projects/xdg/versions) which supports Hippocratic License 2.1.0. I'm going to close this issue now that the patched version is out.

**Comment by dcermak** [comment]
Thank you @bkuhlmann!
